### ISSUE TITLE
If profile is composer installed, "web" (and "vendor") get nested in govcms profile folder.

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/GovCMS#137] opened 2021-03-19 02:41 UTC
This causes issues with running drush updb like:

InfoParserDynamic.php The 'core_version_requirement' key must be present in profiles/contrib/govcms/web/core/profiles/demo_umami/demo_umami.info.yml

PR [#136]

**Comment by joshua-graham-adelphi** [comment] 2021-03-19 02:41
#136

**Comment by pandaskii** [comment] 2021-03-30 05:54
@joshua-graham-adelphi 

Can you please give us the steps to reproduce this issue if possible? thanks

**Comment by joshua-graham-adelphi** [comment] 2021-03-30 06:39
Hi @pandaskii ,

To reproduce, perform the following after git clone.

```bash
# Install or Import govcms
docker-compose up -d
docker-compose exec cli drush si govcms -y
# Test `drush updb` works. 
docker-compose exec cli drush updb
# Test `drush cr` works.
docker-compose exec cli drush cr

# Install composer packages to see which modules are installed / how they work etc.
composer install

# Command `docker-compose exec cli drush cr` now fails.
docker-compose exec cli drush updb
# [ERROR] InfoParserDynamic.php The 'core_version_requirement' key must be present in profiles/contrib/govcms/web/core/profiles/demo_umami/demo_umami.info.yml

# Command `drush cr` now fails too.
docker-compose exec cli drush cr
# [ERROR] InfoParserDynamic.php The 'core_version_requirement' key must be present in profiles/contrib/govcms/web/core/profiles/demo_umami/demo_umami.info.yml
```

**Comment by pandaskii** [comment] 2021-04-22 10:30
@joshua-graham-adelphi 

thinking to remove the following prior to the stable GovCMS D9 2.0.0 release

- https://github.com/govCMS/GovCMS/blob/2.x-develop/docker-compose.yml
- https://github.com/govCMS/GovCMS/blob/2.x-develop/.env.default
- https://github.com/govCMS/GovCMS/blob/2.x-develop/.ahoy.yml

GovCMS has two repos:

https://github.com/govCMS/scaffold - This codebase provides a Drupal GovCMS site ready for hosting on the GovCMS platform (Lagoon).

https://github.com/govCMS/lagoon - to create the images required by Lagoon, using the GovCMS distribution - it is only intended to be used by distribution/platform maintainers

Especially with https://github.com/govCMS/lagoon, we don't need to keep docker-compose.yml in the distribution codebase for distribution/platform maintainers.

Regarding this issue, I think it could be linked to https://github.com/govCMS/GovCMS/blob/7ad5b6cb4a77705935dbc42c8b6171e7f3a64936/composer.json#L198

/app/web/profiles/contrib/govcms/web could be copied by rsync

**Comment by joshua-graham-adelphi** [comment] 2021-04-22 23:42
Indeed it is related to rsync.

Happy with either way , remover docker-compose related files or merge this commit in. (or both, merge commit and then remove when GovCMS 2.0.0 is released).

Just a heads up. Also we should update the README.md to say that https://github.com/govCMS/scaffold is also an option.
Joshua

**Comment by pandaskii** [comment] 2021-05-11 05:57
Close this ticket and we will have the README.md updated in the coming releases :)

**Closed as completed by pandaskii** 2021-05-11 05:57 UTC
